- vulture_os/toolkit/updates/v0.9.92/1_index_logs_ipv6.sh
- vulture_os/toolkit/updates/v0.9.92/2_reset_darwin_filters_ipv6.sh
- UPGRADE : Re-make previous migrations (index_logs & reset_darwin_filters) on IPv6 machines, cause they have failed due to ipv6 support missing
> Release 0.9.92

- .gitignore
add .vscode user folder to gitignore
> GITIGNORE :: Update :: added .vscode user conf directory

- vulture_os/applications/logfwd/config/om_fwd.tpl
- LOG_FORWARDERS : Bad quotes placement in ZipLevel of LogFwd
> Release 0.9.94

- vulture_os/applications/logfwd/config/om_fwd.tpl
- LOG_FORWARDERS :: Fix : Add missing template in log forwarder
> Hotfix 0.9.94

- vulture_os/toolkit/updates/v0.9.6/reset_darwin_filters.sh
- vulture_os/toolkit/updates/v0.9.91/reset_darwin_filters.sh
- vulture_os/toolkit/updates/v0.9.92/1_index_logs_ipv6.sh
- vulture_os/toolkit/updates/v0.9.92/2_reset_darwin_filters_ipv6.sh
- vulture_os/toolkit/updates/v0.9.93/1_darwin_update_conf.py
- vulture_os/toolkit/updates/v0.9.93/2_gui_update_conf.py
- UPGRADE : Add checks in upgrade script to prevent crash if node is not bootstrapped/installed.
> Release 0.9.95

- vulture_os/daemons/cluster.py
- vulture_os/daemons/monitor.py
- vulture_os/daemons/reconcile.py
- vulture_os/gui/crontab/reconcile.py
- vulture_os/vulture_os/settings.py
Add pubsub mechanism for the reconciliation job
> Reconciliation

- vulture_os/gui/crontab/api_clients_parser.py
- vulture_os/gui/static/js/listener.js
- vulture_os/toolkit/api_parser/akamai/akamai.py
- FRONTEND : Automatically select parser only on api log frontends
- API_AKAMAI : Save frontend.last_api_call in database
- API_AKAMAI : Retrieve logs until timestamp of last log is now + urldecode request and response headers
> Release 1.0.4

- vulture_os/services/config/rsyslog_inputs.conf
- vulture_os/services/frontend/models.py
- vulture_os/services/rsyslogd/models.py
- vulture_os/system/templates/system/tenants.html
- vulture_os/system/tenants/models.py
- vulture_os/toolkit/api_parser/akamai/akamai.py
- vulture_os/toolkit/api_parser/api_parser.py
- vulture_os/toolkit/updates/v1.0.10/0_reload_api_frontends_conf.py
- Api parsers : Use tcp inet sockets to communicate between crontab and Rsyslog
- Multi-Tenants : Fix main view error
> Release 1.0.10

- vulture_os/gui/crontab/api_clients_parser.py
- vulture_os/gui/middlewares/api_middleware.py
- vulture_os/services/config/pf.conf
- vulture_os/services/rsyslogd/rsyslog.py
- vulture_os/system/tenants/api.py
- vulture_os/system/tenants/models.py
- vulture_os/system/tenants/urls.py
- vulture_os/toolkit/api_parser/api_parser.py
- vulture_os/toolkit/api_parser/forcepoint/forcepoint.py
- vulture_os/toolkit/api_parser/symantec/symantec.py
- Api parser : Finalize the api forcepoint parser
- Multi-Tenants : Finish api
- Packet Filter : Add anti-scanning rules
- Rsyslog : Fix generation of pstats configuration
- Api middleware : Fix empty body + error message
- Api parser Symantec : Add endDate parameter to prevent logs loss
> Release 1.0.12

- vulture_os/toolkit/api_parser/cybereason/cybereason.py
- vulture_os/toolkit/api_parser/cybereason/cybereason_toolkit.py
- Api_cybereason : Rename some fields and add new ones
> Release 1.0.22

- vulture_os/toolkit/api_parser/cybereason/cybereason.py
- API_Cybereason : Do not retrieve affected devices for malwares, API returns nothing
> Release 1.0.23

- vulture_os/services/migrations/0024_auto_20201228_1710.py
Upgrade failure : Fix migration file
> Release 1.0.26

- vulture_os/services/config/pf.conf
- [FIX] remove unreliable fingerprinting rule
> PF::FIX:: Remove blocking via fingerprinting

- vulture_os/authentication/generic_delete.py
- vulture_os/authentication/portal_template/api.py
- vulture_os/authentication/portal_template/form.py
- vulture_os/authentication/portal_template/models.py
- vulture_os/authentication/portal_template/urls.py
- vulture_os/authentication/portal_template/views.py
- vulture_os/authentication/templates/authentication/ldap_edit.html
- vulture_os/authentication/templates/authentication/portal_template/dialogs.html
- vulture_os/authentication/templates/authentication/portal_template/edit.html
- vulture_os/authentication/templates/authentication/portal_template/errors.html
- vulture_os/authentication/templates/authentication/portal_template/image_edit.html
- vulture_os/authentication/templates/authentication/portal_template/images.html
- vulture_os/authentication/templates/authentication/portal_template/learning.html
- vulture_os/authentication/templates/authentication/portal_template/list.html
- vulture_os/authentication/templates/authentication/portal_template/login.html
- vulture_os/authentication/templates/authentication/portal_template/logout.html
- vulture_os/authentication/templates/authentication/portal_template/message.html
- vulture_os/authentication/templates/authentication/portal_template/otp.html
- vulture_os/authentication/templates/authentication/portal_template/password.html
- vulture_os/authentication/templates/authentication/portal_template/registration.html
- vulture_os/authentication/templates/authentication/portal_template/self.html
- vulture_os/authentication/templates/authentication/portal_template/style.html
- vulture_os/authentication/templates/authentication/user_authentication_edit.html
- vulture_os/authentication/user_portal/api.py
- vulture_os/gui/static/css/custom.css
- vulture_os/gui/static/js/portal/template_edit.js
- vulture_os/workflow/config/haproxy_portal.conf
CRUD for Image in Portal Template
Fix Portal Template write on disk
Fix Haproxy Portal template content
> Image template

- vulture_os/workflow/models.py
- [Workflow] graph did not show/wasn't editable when an authentication portal was linked to it
> HOTFIX:: Workflow graph not showing on GUI when editing workflow with authentication

- vulture_os/toolkit/api_parser/symantec/symantec.py
> Fix symantec catching up

- vulture_os/toolkit/api_parser/netskope/netskope.py
- [Frontend][API Netskope] :: Fix : Fix use of proxy + test get_logs from GUI
> Hotfix 1.2.9_1

- vulture_os/authentication/templates/authentication/user_authentication_edit.html
- vulture_os/authentication/user_portal/views.py
- vulture_os/portal/system/authentications.py
- vulture_os/portal/system/redis_sessions.py
- vulture_os/portal/views/logon.py
- vulture_os/services/config/spoe_session.txt
- vulture_os/services/frontend/config/haproxy_frontend.conf
- [PORTAL] Allow refreshing portal session expiration timeout after each request
- [PORTAL] Create/update the oauth token during SSO authentication
-  [OAUTH_SESSION] Correctly set and get the Oauth scope in Redis
> Portal : Allow session refresh during requests

- vulture_os/authentication/auth_access_control/api.py
- vulture_os/authentication/auth_access_control/form.py
- vulture_os/authentication/auth_access_control/models.py
- vulture_os/authentication/auth_access_control/views.py
- vulture_os/authentication/generic_delete.py
- vulture_os/authentication/portal.py
- vulture_os/authentication/templates/authentication/access_control/edit.html
- vulture_os/gui/static/js/portal/auth_access_control.js
- vulture_os/gui/static/js/workflow.js
- vulture_os/gui/static/js/workflow_form.js
- vulture_os/portal/system/authentications.py
- vulture_os/portal/views/logon.py
- vulture_os/workflow/api.py
- vulture_os/workflow/models.py
- vulture_os/workflow/templates/main/workflow_edit.html
- vulture_os/workflow/views.py
- [PORTAL] Authentication filtering capabilities on user's scopes
- [WORKFLOW] filter user's scope with authentication filters when some are assigned
- [AUTHENTICATION FILTERS] add additional operators to rules
- [WORKFLOW] [GUI] allow setting an authentication filtering when a Portal is set
- [PORTAL] [GUI] rename 'Access Control' to 'Authentication Filters'
- [WORKFLOW] [GUI] allow setting a Portal only when necessary
- [WORKFLOW] [GUI] allow changing a Portal by editing the node
- [WORKFLOW] validate entire Workflow before saving model(s)
- [WORKFLOW] prevent removing workflow when Portal or Authentication filtering rules are deleted
> Add UserScope Filtering rules to Workflows with a Portal

- vulture_os/applications/reputation_ctx/config/haproxy_backend.conf
- vulture_os/authentication/portal_template/config/haproxy_backend.conf
- vulture_os/authentication/user_portal/config/haproxy_portal.conf
- vulture_os/authentication/user_portal/views.py
- vulture_os/darwin/access_control/config/haproxy_test.conf
- vulture_os/darwin/log_viewer/config/haproxy_backend_defender.conf
- vulture_os/darwin/log_viewer/config/haproxy_spoe_defender.conf
- vulture_os/services/config/spoe_session.txt
- vulture_os/services/frontend/config/haproxy_frontend.conf
- vulture_os/services/haproxy/models.py
- vulture_os/toolkit/updates/v1.3.2/0_refresh_spoe_session.py
- vulture_os/toolkit/updates/v1.3.2/1_reload_frontends_auth_conf.py
- vulture_os/toolkit/updates/v1.3.2/2_reload_backends_conf.py
- vulture_os/toolkit/updates/v1.3.2/3_reload_portals_conf.py
- vulture_os/workflow/config/haproxy_portal.conf
- vulture_os/workflow/views.py
- [PORTAL] Parasite redirections when user is connected
- [HAPROXY] Prevent configuration errors on LF at the end of files
> Release 1.3.2

- home/jails.apache/.zfs-source/usr/local/etc/apache24/portal-httpd.conf
- vulture_os/authentication/user_portal/config/haproxy_portal.conf
- vulture_os/toolkit/updates/v1.3.3/0_reload_haproxy_auth.py
- vulture_os/toolkit/updates/v1.3.3/1_update_portal-httpd_config.sh
- vulture_os/workflow/config/haproxy_portal.conf
- [PORTAL][HTTPD] Improve performances of portal httpd service, by increasing process related directives
- [PORTAL][HAPROXY] Remove check of haproxy backends (portal), to prevent portal overload with multiple authentication workflows
> Release 1.3.3

- vulture_os/toolkit/api_parser/harfanglab/harfanglab.py
- **[API-HARFANGLAB]** Add missing proxy in http requests
- **[API-HARFANGLAB]** Fix last_api_call set on empty response
> Release 1.3.8

- vulture_os/toolkit/api_parser/cybereason/cybereason.py
- **[FRONTEND][API][Cybereason]** Parser not using proxy configuration while executing query on API
- **[FRONTEND][API][Cybereason]** Malops comments format was dict instead of list
> Version 1.3.13

- vulture_os/authentication/auth_access_control/urls.py
- vulture_os/authentication/idp/urls.py
- vulture_os/authentication/portal_template/urls.py
- vulture_os/darwin/defender_policy/urls.py
- vulture_os/darwin/policy/urls.py
- vulture_os/gui/urls.py
- vulture_os/system/tenants/urls.py
- vulture_os/system/vm/urls.py
- vulture_os/system/zfs/urls.py
- [API][URLS] uniformize URLs to work with and without the trailing '/'
> API_URLS::ADDED:: URLs with and without trailing '/' to uniformize

- home/jails.apache/.zfs-source/usr/local/etc/gunicorn.d/portal.conf.py
- home/jails.apache/.zfs-source/usr/local/etc/rc.d/gunicorn
- vulture_os/authentication/auth_access_control/urls.py
- vulture_os/authentication/idp/urls.py
- vulture_os/authentication/portal_template/urls.py
- vulture_os/darwin/defender_policy/urls.py
- vulture_os/darwin/policy/urls.py
- vulture_os/gui/urls.py
- vulture_os/system/tenants/urls.py
- vulture_os/system/vm/urls.py
- vulture_os/system/zfs/urls.py
- [PORTAL] [GUNICORN CONF] service didn't listen on jail's IPv6 address (no connection from IPv6 networks)
- [API][URLS] uniformize URLs to work with and without the trailing '/'
> Release 1.7.1

- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/toolkit/api_parser/utils.py
- vulture_os/toolkit/api_parser/vadesecure_o365/vadesecure_o365.py
- [PARSER][API] New API parser Vadesecure for Microsoft O365
> New API parser Vadesecure O365

- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/toolkit/api_parser/utils.py
- vulture_os/toolkit/api_parser/vadesecure_o365/vadesecure_o365.py
- [PARSER][API] New API parser Vadesecure for Microsoft O365
> Beta 1.8.0

- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/toolkit/api_parser/blackberry_cylance/blackberry_cylance.py
- vulture_os/toolkit/api_parser/utils.py
- [API][PARSER] New API parser Blackberry Cylance
> API_PARSER::ADDED:: New API parser Blackberry Cylance

- vulture_os/applications/backend/config/haproxy_backend.conf
- vulture_os/applications/backend/models.py
- vulture_os/darwin/access_control/models.py
- vulture_os/gui/static/js/access_control.js
- vulture_os/services/frontend/config/haproxy_frontend.conf
- vulture_os/services/frontend/models.py
- vulture_os/workflow/models.py
- [HAPROXY][FRONTEND] ACLs generated were wrong on some conditions
- [HAPROXY][BACKEND] ACLs generated were wrong on some conditions
- [ACLS] patterns with spaces given on GUI weren't quoted in configuration
- [GUI][ACL] Print the correct boolean syntax for haproxy on the edition preview
> ACLs corrections

- vulture_os/toolkit/api_parser/sentinel_one/sentinel_one.py
- [API_LOGGER][SENTINELONE] Use correct timestamp from 'activity' alerts to update last_api_call
- [API_LOGGER][SENTINELONE] add a 'to' argument to fix queried intervals and avoid gaps between executions
- [API_LOGGER][SENTINELONE] better logging of parser execution
> API SENTINEL ONE: Fixes and improvements

- vulture_os/portal/views/logon.py
- vulture_os/toolkit/system/hashes.py
- [PORTAL] Create a new portal session value from safe generator if value taken from client cookies is not formatted correctly or is not present in current cache
- [UTILS] [ HASHES] validation function for hash digest's format (length and characters used)
> Beta 1.12.1

- vulture_os/portal/views/logon.py
- vulture_os/toolkit/api_parser/reachfive/reachfive.py
- vulture_os/toolkit/system/hashes.py
- [PORTAL] Create a new portal session value from safe generator if value taken from client cookies is not formatted correctly or is not present in current cache
- [UTILS][HASHES] validation function for hash digest's format (length and characters used)
> Version 1.12.1

- vulture_os/toolkit/api_parser/harfanglab/harfanglab.py
> Harfanglab duplicate logs

- vulture_os/services/frontend/views.py
- vulture_os/toolkit/http/headers.py
- [API][FRONTEND] Avoid errors while trying to create new header's objects on a Frontend
- [FRONTEND][HEADERS] Handle headers' values with spaces, simple quotes and double quotes
> Fixes to Headers creation and handling

- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/toolkit/api_parser/utils.py
- vulture_os/toolkit/api_parser/waf_cloudflare/waf_cloudflare.py
- [API][PARSER] New api parser WAF Cloudflare
> Waf cloudflare

- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/toolkit/api_parser/gsuite_alertcenter/gsuite_alertcenter.py
- vulture_os/toolkit/api_parser/utils.py
> NEW PARSEUR : API gsuite [google alertcenter]

- vulture_os/toolkit/api_parser/harfanglab/harfanglab.py
- [API-PARSER][HARFANGLAB] Fix duplicated alerts collected
> Fix Api-harfanglab replay

- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/toolkit/api_parser/sophos_cloud/sophos_cloud.py
- vulture_os/toolkit/api_parser/utils.py
- [API][PARSER] New api parser SophosCloud
> New api collector sophos_cloud

- vulture_os/services/frontend/form.py
- [FRONTEND] Fix syntax error in fields list, causing 500 error when creating/editing new listener
> Release 1.16.1

- vulture_os/toolkit/api_parser/gsuite_alertcenter/gsuite_alertcenter.py
- vulture_os/toolkit/api_parser/office365/office365.py
- vulture_os/toolkit/api_parser/proofpoint_pod/proofpoint_pod.py
- vulture_os/toolkit/api_parser/sophos_cloud/sophos_cloud.py
- vulture_os/toolkit/api_parser/waf_cloudflare/waf_cloudflare.py
- [API PARSER] WAF Cloudflare proxy support
- [API PARSER] Office365 proxy support
- [API PARSER] Gsuite proxy support
- [API PARSER] Sophos proxy support
- [API PARSER] ProofpointPod proxy support
> Add: Proxy support for missing technos

- vulture_os/toolkit/api_parser/gsuite_alertcenter/gsuite_alertcenter.py
- vulture_os/toolkit/api_parser/office365/office365.py
- vulture_os/toolkit/api_parser/proofpoint_pod/proofpoint_pod.py
- vulture_os/toolkit/api_parser/sophos_cloud/sophos_cloud.py
- vulture_os/toolkit/api_parser/waf_cloudflare/waf_cloudflare.py
- vulture_os/toolkit/updates/v1.17.0/0_update_api_parsers.py
- [API PARSER] WAF Cloudflare proxy support
- [API PARSER] Office365 proxy support
- [API PARSER] Gsuite proxy support
- [API PARSER] Sophos proxy support
- [API PARSER] ProofpointPod proxy support
> Version 1.17.0

- vulture_os/system/error_templates/api.py
- vulture_os/system/error_templates/models.py
- vulture_os/system/error_templates/urls.py
- [API.PY] GET, POST, PUT, DELETE API methods for adding, mmodifying and deleting http messages
- [URLS.PY] URLS paths to access the API
- [MODELS.PY] Added fields option for filtering to ErrorTemplate's to_dict function
- [MODELS.PY] Changed to_dict to include frontends related to the Error Template in to_dict function
> [HTTP_MESSAGE] Added API for Http Messages

- vulture_os/applications/logfwd/views.py
- vulture_os/services/frontend/views.py
- [LOGFWD][VIEWS.PY] Replacing old name with new name in log condition when the log forwarder is updated
- [FRONTEND][VIEWS.PY] Fixed no error when an already existing server is used in a new frontend
- [FRONTEND][VIEWS.PY] Removed trailing spaces
> [LOGFWD][FRONTEND] FIXED::Update of related frontends for modified log forwarders

- vulture_os/applications/backend/views.py
- [VIEWS.PY] Included available darwin sockets to view for backend_clone
> [BACKEND]Fixed::Unable to save cloned backend

- vulture_os/gui/views/install.py
- vulture_os/system/cluster/models.py
- vulture_os/system/cluster/views.py
- vulture_os/toolkit/network/network.py
- vulture_os/toolkit/system/rc.py
- vulture_os/toolkit/updates/v0.9.92/1_index_logs_ipv6.sh
- vulture_os/toolkit/updates/v0.9.92/2_reset_darwin_filters_ipv6.sh
- Added await_result function to MessageQueue to wait and obtain result of the operation
- Added get_rc_config function that gets value of variables in main and custom rc config files
- Added set_rc_config function that sets value of variables in main and custom rc config files
- Added ability to call the above functions via the node or cluster(only for set_rc_config) API request
- Updating changes of network ips from GUI to rc configuration
- Changed the use of management.ip file to using rc configuration
- Changed the response of node API request to include MessageQueue instance
- Replaced apache configuration's reloads to apache service reloads (configurations are not templated)
> FIXED::Modification of node network ips from CLI

- vulture_os/applications/logfwd/config/om_elasticsearch.tpl
- vulture_os/applications/logfwd/config/om_fwd.tpl
- vulture_os/applications/logfwd/form.py
- vulture_os/applications/logfwd/models.py
- vulture_os/applications/templates/apps/logfwd_LogOMElasticSearch.html
- vulture_os/applications/templates/apps/logfwd_LogOMFWD.html
- vulture_os/services/config/rsyslog_inputs.conf
- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/templates/services/frontend_edit.html
- [FRONTEND][LOG] add (advanced) parameters for rate-limiting on TCP log listeners
- [LOG_FORARDER][SYSLOG] add (advanced) parameters for output rate-limiting on syslog forwarder
- [LOG_FORARDER][ELASTICSEARCH] add (advanced) parameters for output rate-limiting on elasticsearch forwarder
> Log rate-limiting implementation

- vulture_os/toolkit/api_parser/harfanglab/harfanglab.py
- [FRONTEND][API_COLLECTOR][HARFANGLAB] Prevent duplicated collected alerts by using advanced API parameters
> HARFANGLAB - Prevent duplicated alerts

- vulture_os/toolkit/api_parser/sentinel_one/sentinel_one.py
[FRONTEND][API_COLLECTOR][SENTINELONE] Prevent duplicated events by modifying last_api_call variable
> Fix SentinelOne connector

- vulture_os/toolkit/api_parser/gsuite_alertcenter/gsuite_alertcenter.py
Add proxy ipv4/6 support for gsuite alertcenter
> Gsuite proxy httplib2 

- CHANGELOG
- home/jails.apache/.zfs-source/home/vlt-os/bootstrap/configure
- vulture_os/authentication/idp/api.py
- vulture_os/authentication/idp/authentication.py
- vulture_os/authentication/idp/urls.py
- vulture_os/authentication/ldap/tools.py
- vulture_os/authentication/user_portal/models.py
- vulture_os/darwin/access_control/models.py
- vulture_os/portal/system/authentications.py
- vulture_os/portal/system/redis_sessions.py
- vulture_os/portal/views/logon.py
- vulture_os/toolkit/api_parser/gsuite_alertcenter/gsuite_alertcenter.py
- vulture_os/toolkit/api_parser/symantec/symantec.py
- vulture_os/toolkit/auth/ldap_client.py
- vulture_os/toolkit/updates/v2.1.0/0_reload_acl_workflows.py
- vulture_os/vulture_os/settings.py
- [LDAP_CLIENT] Use escape_dn_chars() instead of escape_filter_chars() in search_user() for sanitation
- [OAUTH] Ensure 'sub' is present in oauth2 tokens
- [BOOTSTRAP] [CONFIGURE.SH] wrong order of imports in script
- [API_PARSER] [SYMANTEC] Handle cases where the token is not in archive
- [OUAUTH] [TOKEN] exp and iat from /token are correctly set when returning an oauth token
- [ACLS] Avoid multiple declarations of the same set of rules in generated Haproxy configurations
- [IDP_API] Improved logging to include systematic portal, repo, user (when available) and action
- [IDP] [API] New APIs to manage oauth2 tokens creation
- Create a new token for a specific user, on a specific portal and repository
- User must authenticate themselves with a valid oauth token
- Claims will be created …
> Version 2.1.0

- vulture_os/toolkit/api_parser/imperva/imperva.py
- [API_PARSER][Imperva] Download multiple files at once, to prevent delay
> API_PARSER :: Imperva : Fix delay increasing

- vulture_os/toolkit/api_parser/symantec/symantec.py
- [API_PARSER][Symantec] Fix token retrieve from downloaded archive tail
> API_PARSER :: Symantec : Fix token retrieve

- vulture_os/toolkit/api_parser/imperva/imperva.py
- vulture_os/toolkit/api_parser/symantec/symantec.py
- [API_PARSER][IMPERVA] Fix typo in logger that makes the process crash
- [API_PARSER][SYMANTEC] Fix extracting token from downloaded archive
> [API_PARSERs][Symantec][Imperva] Fixes

- CHANGELOG
- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/toolkit/api_parser/proofpoint_casb/proofpoint_casb.py
- vulture_os/toolkit/api_parser/utils.py
- Collecteur de logs Proofpoint CASB
> API_PARSER :: Proofpoint CASB

- vulture_os/toolkit/api_parser/defender/defender.py
- vulture_os/toolkit/api_parser/nozomi_probe/nozomi_probe.py
- [API_PARSER][DEFENDER] GUI 'test' button where always returning "Success" even if credentials where wrong
> [API_PARSER][Defender] Fix test error return

- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/toolkit/api_parser/proofpoint_trap/proofpoint_trap.py
- vulture_os/toolkit/api_parser/utils.py
Add new parser api_proofpoint_trap
> ADD NEW PARSER API_PROOFPOINT_TRAP

- vulture_os/toolkit/api_parser/blackberry_cylance/blackberry_cylance.py
- [API_PARSER][BLACKBERRY_CYLANCE] Fix update of last_api_call + prevent stagnation
> [API_PARSER][Blackberry_cylance] Fix last_api_call update + prevent stagnation

- vulture_os/toolkit/api_parser/netskope/netskope.py
- **[API_PARSER][Netskope]** Fix update of last_api_call + prevent cursor stagnation
> [API_PARSER][Netskope] Fix last_api_call update

- vulture_os/toolkit/api_parser/akamai/akamai.py
- [API_PARSER][Akamai] Gargantually increase performance by using Processes instead of Threads
> [API_PARSER][Akamai] Gargantually increase performance

- vulture_os/toolkit/api_parser/proofpoint_trap/proofpoint_trap.py
- Removed filter in request
- Added filter before treatment, to drop incident logs with state "closed" or "ignored"
> FIX API_PROOFPOINT_TRAP

- vulture_os/toolkit/api_parser/proofpoint_trap/proofpoint_trap.py
- Add treatment delay of 15 minutes to have the alerts after their update
- Get more incident information, including incident severity
> [API_PARSER][PROOFPOINT_TRAP] Fix severity

- vulture_os/toolkit/api_parser/waf_cloudflare/waf_cloudflare.py
- [API_PARSER][Waf_CloudFlare] Fix ram explosion + improve resilience by downloading by bulks
> [API_PARSER][Waf_CloudFlare] Fix ram explosion

- vulture_os/toolkit/api_parser/akamai/akamai.py
[API_AKAMAI] Fix process authorization problem by making processes variables attributes of Akamai class and removing the use of processes in test function.
> [API_AKAMAI] Fix HBSD13 SemLock issue

- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/toolkit/api_parser/cybereason/cybereason.py
Cybereason has a new API, this evolve has create to support thier new endpoint
> [API_PARSER][CYBEREASON] Fix new endpoint

- CHANGELOG
- home/jails.apache/.zfs-source/home/vlt-os/scripts/replica_rename.py
- vulture_os/applications/logfwd/views.py
- vulture_os/applications/reputation_ctx/models.py
- vulture_os/darwin/policy/api.py
- vulture_os/gui/views/install.py
- vulture_os/services/darwin/darwin.py
- vulture_os/services/frontend/views.py
- vulture_os/services/rsyslogd/rsyslog.py
- vulture_os/system/cluster/views.py
- vulture_os/system/config/views.py
- vulture_os/system/tenants/models.py
- vulture_os/system/tenants/views.py
- vulture_os/toolkit/updates/v0.9.1/rsyslog_update_conf.py
- vulture_os/toolkit/updates/v1.0.1/6_rewrite_darwin_config.py
- vulture_os/toolkit/updates/v1.0.10/0_reload_api_frontends_conf.py
- vulture_os/toolkit/updates/v1.0.2/1_update_frontends_darwin.py
- vulture_os/toolkit/updates/v1.0.8/0_reload_reputation_contexts.py
- vulture_os/toolkit/updates/v1.0.9/1_reload_api_frontends_conf.py
- vulture_os/toolkit/updates/v1.0/2_rsyslog_update_conf.py
- vulture_os/toolkit/updates/v1.12.0/0_reload_haproxy_logs.py
- vulture_os/toolkit/updates/v1.17.0/0_update_api_parsers.py
- vulture_os/toolkit/updates/v1.3.6/0_reload_api_frontends_conf.py
- vulture_os/toolkit/updates/v2.0.0/0_remove_darwin_filters.py
- vulture_os/toolkit/updates/v2.0.0/4_remove_internal_dashboard_forwarder.py
- vulture_os/toolkit/updates/v2.2.2/1_update_default_tenant.py
- [RSYSLOG] Only restart service once after modifying configuration files
> RSYSLOG::FIXED:: Only restart service once all configuration files are written/rebuilt

- vulture_os/toolkit/api_parser/ms_sentinel/ms_sentinel.py
**Added**
[MS_SENTINEL] Add entities information in the logs
> [MS_SENTINEL] Add entities in the logs

- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/toolkit/api_parser/trendmicro_visionone/trendmicro_visionone.py
- vulture_os/toolkit/api_parser/utils.py
New parser API_TRENDMICRO_VISIONONE
> [API_PARSER][TRENDMICRO_VISIONONE] New parser

- vulture_os/toolkit/api_parser/trendmicro_visionone/trendmicro_visionone.py
FIX TRENDMICRO_VISIONONE : fix format of logs and update of timestamp
> [API_PARSER] TRENDMICRO_VISIONONE : fix format of logs and update of timestamp

- vulture_os/toolkit/api_parser/harfanglab/harfanglab.py
Add a delay before request API harfanglab, to let enough time at harfanglab to put all logs available
> [API_PARSER] HARFANGLAB Delay request at the API

- vulture_os/toolkit/api_parser/trendmicro_visionone/trendmicro_visionone.py
[API_PARSER][TRENDMICRO_VISIONONE] Fix logs formatting
> [API_PARSER][TRENDMICRO_VISIONONE] Fix logs formatting

- vulture_os/toolkit/api_parser/proofpoint_tap/proofpoint_tap.py
> [API_PARSER] PROOFPOINT_TAP Fix logger error

- vulture_os/toolkit/api_parser/trendmicro_visionone/trendmicro_visionone.py
###Change
- [API_PARSER][TRENDMICRO_VISIONONE] fix formatting of logs
> [API_PARSER][TRENDMICRO_VISIONONE] fix formatting of logs

- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/toolkit/api_parser/cisco_duo/cisco_duo.py
- vulture_os/toolkit/api_parser/utils.py
- vulture_os/workflow/generic_list.py
- [API_PARSER] New collector API CISCO_DUO
> [API_PARSER][CISCO_DUO] New collector

- vulture_os/services/frontend/config/haproxy_frontend.conf
- [FRONTEND] HAProxy template now allow an IDP outside a workflow
> [FRONTEND] Allow a standalone IDP with a listener outside a workflow

- CHANGELOG
- vulture_os/applications/logfwd/config/om_elasticsearch.tpl
- vulture_os/applications/logfwd/form.py
- vulture_os/applications/logfwd/models.py
- vulture_os/applications/templates/apps/logfwd_LogOMElasticSearch.html
- [LOGFORWARDER] [ELASTICSEARCH] Enable ELS>=8 compatibility
- [LOGFORWARDER] [ELASTICSEARCH] Ensure index patterns are kept to lowercase
- [LOGFORWARDER] [ELASTICSEARCH] Avoid newline problems in generated configurations
> [LOGFORWARDER] Fix logforward to elastic8

- vulture_os/toolkit/api_parser/imperva/imperva.py
-  Fix duplicates files downloading
-  Fix crash if file does not exist
> [API_PARSER][IMPERVA] Fixes

- CHANGELOG
- vulture_os/applications/logfwd/config/om_hiredis.tpl
- vulture_os/applications/logfwd/form.py
- vulture_os/applications/logfwd/models.py
- vulture_os/applications/templates/apps/logfwd_LogOMHIREDIS.html
- vulture_os/services/config/rsyslog_inputs.conf
- vulture_os/services/rsyslogd/config/rsyslog_darwin/ruleset.conf
- vulture_os/services/rsyslogd/config/rsyslog_template_generic_json.conf
- vulture_os/services/rsyslogd/config/rsyslog_template_pstats.conf
- [LOG_FORWARDER] [HIREDIS] Ability to specify that the destination key is a dynamic template
- [LOG_FORWARDER] [HIREDIS] Use updated templates <name>_json
> [FEATURE] Allow to define a dynamic key for the Redis LogForwarder

- CHANGELOG
- vulture_os/gui/static/js/listener.js
- vulture_os/services/frontend/models.py
- vulture_os/services/frontend/views.py
- [FRONTEND] Disable logforwarder if logging disabled
- [FRONTEND] Reload services only on involved nodes
> [FRONTEND] Disable logforwarder if logging disabled

- CHANGELOG
- vulture_os/applications/logfwd/config/om_elasticsearch.tpl
- vulture_os/applications/logfwd/config/om_file.tpl
- vulture_os/applications/logfwd/config/om_hiredis.tpl
- vulture_os/applications/logfwd/config/om_mongodb.tpl
- vulture_os/applications/logfwd/config/om_relp.tpl
- vulture_os/applications/logfwd/form.py
- vulture_os/applications/logfwd/models.py
- vulture_os/applications/templates/apps/logfwd_LogOMElasticSearch.html
- vulture_os/applications/templates/apps/logfwd_LogOMFile.html
- vulture_os/applications/templates/apps/logfwd_LogOMHIREDIS.html
- vulture_os/applications/templates/apps/logfwd_LogOMMongoDB.html
- vulture_os/applications/templates/apps/logfwd_LogOMRELP.html
- [LOGFORWARDER] send_as_raw option for all LogForwarders
> [LOGFORWARDER] implements new send_as_raw feature for LogForwarder in gui

- CHANGELOG
- vulture_os/services/frontend/views.py
**Changed**
Delete old conf when the mode is changed to avoid a duplicated conf
> [FRONTEND] Remove old conf when the mode is changed to avoid a duplicated conf

- CHANGELOG
- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/toolkit/api_parser/retarus/retarus.py
- vulture_os/toolkit/api_parser/utils.py
> [API_PARSER][RETARUS] New parser RETARUS

- CHANGELOG
- vulture_os/daemons/monitor.py
- vulture_os/gui/crontab/api_clients_parser.py
- vulture_os/gui/management/commands/toggle_maintenance.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/system/cluster/models.py
- vulture_os/system/templates/system/cluster.html
- https://github.com/VultureProject/vulture-base/pull/99
- [CLUSTER] Node state and heartbeat
- [GUI] API collector node runner selector
> [CLUSTER] Node state and API collector runner selector

- CHANGELOG
- vulture_os/authentication/ldap/form.py
- vulture_os/authentication/ldap/models.py
- vulture_os/authentication/ldap/tools.py
- vulture_os/authentication/templates/authentication/ldap_edit.html
- vulture_os/toolkit/auth/ldap_client.py
- [LDAP] Allow to define custom ObjectClasses for Users and Groups when creating them through Vulture
> LDAP: Allow to define custom ObjectClasses for Users and Groups

- CHANGELOG
- vulture_os/applications/logfwd/config/om_elasticsearch.tpl
- vulture_os/applications/logfwd/config/om_kafka.tpl
- vulture_os/applications/logfwd/form.py
- vulture_os/applications/logfwd/models.py
- vulture_os/applications/logfwd/views.py
- vulture_os/applications/templates/apps/logfwd.html
- vulture_os/applications/templates/apps/logfwd_LogOMKAFKA.html
- vulture_os/services/config/rsyslog_inputs.conf
- vulture_os/services/pf/pf.py
- vulture_os/services/rsyslogd/rsyslog.py
- vulture_os/system/cluster/models.py
**Added**
[GUI][LOGFORWARDER] Kafka logforwarder
> [LOGFORWARDER] Implements new logforwarder for kafka backend

- vulture_os/toolkit/api_parser/sentinel_one/sentinel_one.py
- **[API_COLLECTOR][SENTINEL_ONE]** Fix account_type="user service" authentication routine
> [API_COLLECTOR][SENTINEL_ONE] Fix authentication routine

- CHANGELOG
- vulture_os/authentication/user_portal/models.py
- vulture_os/system/pki/models.py
- vulture_os/toolkit/updates/v2.11.0/0_update_default_tls_profile.py
- [TLS] Update default parameters for accepted TLS versions
> TLS::CHANGED:: Update default parameters for accepted TLS versions

- CHANGELOG
- vulture_os/applications/backend/views.py
- vulture_os/services/frontend/views.py
- [WORKFLOW] When a frontend/backend is used in a Workflow his type can't be changed anymore
> [WORKFLOW] Add type change check when front/back associated to workflow

- CHANGELOG
- vulture_os/toolkit/api_parser/cisco_duo/cisco_duo.py
- [API_COLLECTOR][CISCO_DUO] Add log.metadata null check to avoid NoneType Error
> [API_COLLECTOR][CISCO_DUO] Fix log.metadata null check

- CHANGELOG
- vulture_os/gui/static/js/listener.js
- vulture_os/services/config/filebeat_inputs.conf
- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/frontend/views.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/toolkit/api_parser/api_parser.py
- vulture_os/toolkit/network/network.py
- [FRONTEND] Custom proxy for api parser
> [FRONTEND] Custom proxy for api parser

- CHANGELOG
- vulture_os/portal/system/authentications.py
- vulture_os/portal/system/redis_sessions.py
- vulture_os/portal/views/logon.py
###Fixed
- [PORTAL] [IDP] Prevent refreshing a token created with an other IDP
> [PORTAL][IDP] Prevent refreshing a token created with an other IDP

- CHANGELOG
- vulture_os/portal/system/authentications.py
- vulture_os/portal/system/redis_sessions.py
- vulture_os/portal/system/self_actions.py
- vulture_os/portal/views/learning.py
- [PORTAL] [SSO] Avoid autologon password retrieval failures
> PORTAL_SSO::FIXED:: Avoid autologon password retrieval failures

- vulture_os/toolkit/api_parser/trendmicro_visionone/trendmicro_visionone.py
- [API_PARSER] [TRENDMICRO_VISIONONE] Fix Alerts endpoint params
> [API_PARSER][TRENDMICRO_VISIONONE] Fix Alerts endpoint params

- CHANGELOG
- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/toolkit/api_parser/utils.py
- vulture_os/toolkit/api_parser/vectra/vectra.py
- [API_PARSER] New parser API_VECTRA
> [API_PARSER][VECTRA] New parser

- CHANGELOG
- vulture_os/gui/management/commands/get_api_key.py
- vulture_os/system/config/api.py
- vulture_os/system/config/urls.py
- vulture_os/system/config/views.py
- [**GUI**] Add command get_api_get to retrieve cluster_api_key with grains
- [**SYSTEM**] Change syntax of config api
> [SALT] Add command get_api_key and change config api to config system with salt

- CHANGELOG
- vulture_os/portal/settings.py
- vulture_os/portal/views/logon.py
- [OAUTH2] [USERINFO] Allow to validate JWT in /userinfo with new OpenID connector's parameters
> [PORTAL] Add /userinfo authentication using JWT

- CHANGELOG
- vulture_os/services/frontend/models.py
- vulture_os/services/frontend/views.py
- [FRONTEND] New last_update_time field
> [FRONTEND] New last_update_time field

- CHANGELOG
- vulture_os/authentication/user_portal/config/haproxy_portal.conf
- vulture_os/services/frontend/config/haproxy_frontend.conf
- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/workflow/config/haproxy_portal.conf
- vulture_os/workflow/models.py
- [FRONTEND] [TIMEOUTS] Incoherent "timeout connect" in Frontend attributes
- [HAPROXY] [CONF] Split Frontend and Workflow config to improve performance
- [HAPROXY] [CONF] Change test config names by uuids
- [WORKFLOW] Re-allow multiple workflows on the same FQDN with sub-paths
- [HAPROXY] Ensure X-Forwarded-proto header is correctly set on Frontend configuration
> [HAPROXY] Split Frontend and Workflow config to improve performance

- CHANGELOG
- vulture_os/gui/static/js/workflow.js
- vulture_os/gui/static/js/workflow_form.js
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/workflow/config/haproxy_portal.conf
- vulture_os/workflow/form.py
- vulture_os/workflow/models.py
- vulture_os/workflow/templates/main/workflow_edit.html
- vulture_os/workflow/views.py
- [GUI] [WORKFLOW] CORS policy settings
- [HAPROXY] [CONF] CORS policy into config generation
> [WORKFLOW] Add CORS policy settings

- CHANGELOG
- vulture_os/toolkit/api_parser/harfanglab/harfanglab.py
- [**HARFANGLAB**] Fetch new endpoint for Threats logs
> [API_PARSER][HARFANGLAB] Evol:: Add threats endpoint

- CHANGELOG
- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/toolkit/api_parser/apex/apex.py
- vulture_os/toolkit/api_parser/utils.py
- [API_PARSER] New parser API_APEX
> [API_PARSER][APEX]

- CHANGELOG
- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/frontend/views.py
- vulture_os/services/rsyslogd/models.py
- [FRONTEND] Deploy a listener (of type FILE, Redis, Kafka) on every node when listening_node is empty
> [FRONTEND] Deploy a listener on every node when listening_node is empty

- CHANGELOG
- vulture_os/toolkit/api_parser/sentinel_one_mobile/sentinel_one_mobile.py
- [**SENTINEL_ONE_MOBILE**] Fix try..except raises
> [API_PARSER][SENTINEL_ONE_MOBILE] Fix try..except raises

- CHANGELOG
- requirements.in
- requirements.txt
- vulture_os/toolkit/api_parser/forcepoint/forcepoint.py
- [**FORCEPOINT**] Fix update lock to prevent multiprocess
- [**FORCEPOINT**] Use a safer alternative to XML decoding
> [API_PARSER][FORCEPOINT] Fix update lock to prevent multiprocess

- CHANGELOG
- vulture_os/applications/backend/views.py
- vulture_os/authentication/user_portal/views.py
- vulture_os/darwin/access_control/views.py
- vulture_os/services/frontend/models.py
- vulture_os/system/config/views.py
- vulture_os/system/pki/views.py
- vulture_os/workflow/models.py
- [WORKFLOW] Trigger build_conf on various changes
> [WORKFLOW] Trigger build_conf on various change across GUI

- CHANGELOG
- vulture_os/applications/backend/views.py
- vulture_os/services/frontend/config/haproxy_frontend.conf
- vulture_os/services/frontend/models.py
- vulture_os/workflow/views.py
- [HAPROXY] Wrong backend timeout caused by the new intermediate backend
- [WORKFLOW] Correctly update Haproxy's old Frontend configuration when a different one is choosen on a Workflow
> [HAPROXY] Wrong backend timeout caused by the new intermediate backend

- CHANGELOG
- home/jails.apache/.zfs-source/home/vlt-os/scripts/write_cert.sh
- vulture_os/gui/views/install.py
- vulture_os/system/pki/api.py
- [SYSTEM] [PKI] Fix wrong ca.key after cluster_join
> [SYSTEM] [PKI] Fix wrong ca.key after cluster_join

- CHANGELOG
- vulture_os/toolkit/api_parser/api_parser.py
- vulture_os/toolkit/redis/redis_base.py
- [API_PARSER] Connect automatically to redis matser
> [API_PARSER] Connect automatically to redis matser

- CHANGELOG
- vulture_os/applications/logfwd/config/om_elasticsearch_pre.tpl
- vulture_os/applications/logfwd/form.py
- vulture_os/applications/logfwd/models.py
- vulture_os/applications/logfwd/views.py
- vulture_os/applications/templates/apps/logfwd_LogOMElasticSearch.html
- vulture_os/services/frontend/models.py
- vulture_os/services/rsyslogd/config/rsyslog_ruleset_generic_json/ruleset.conf
- vulture_os/services/rsyslogd/config/rsyslog_ruleset_raw_to_json/ruleset.conf
- [LOGOMELASTICSEARCH] Handle log insertion errors returned by elasticsearch
> [LOGOMELASTICSEARCH] Handle log insertion errors returned by elasticsearch

- CHANGELOG
- vulture_os/toolkit/api_parser/rapid7_idr/rapid7_idr.py
- [API_PARSER][RAPID7_IDR] Add priority field in the logs
> [API_PARSER][RAPID7_IDR] Add priority field in the logs

- CHANGELOG
- vulture_os/gui/crontab/feed.py
- vulture_os/vulture_os/settings.py
- [CRON] Only update Reputation Context DB on Wednesdays and Saturdays at 2am
- [CRON] Only update security audits every night at 11pm
> Version 2.15.2

- CHANGELOG
- vulture_os/services/frontend/models.py
- vulture_os/toolkit/api_parser/apex/apex.py
- [API_PARSER] [APEX] Use the page_token parameter to prevent duplication of logs
> [API_PARSER][APEX] Use page_token parameter to prevent duplication of logs

- CHANGELOG
- vulture_os/toolkit/api_parser/cybereason/cybereason.py
- **[CYBEREASON]** Evol on malops
> [API_PARSER][CYBEREASON] Evol on malops

- CHANGELOG
- vulture_os/toolkit/api_parser/harfanglab/harfanglab.py
- [API_PARSER] [HARFANGLAB] Increase the limit of logs in request and reduce time range of requests
> [API_PARSER] [HARFANGLAB] Increase the limit of logs in request and reduce time range of requests

- CHANGELOG
- vulture_os/toolkit/api_parser/csc_domainmanager/csc_domainmanager.py
- **[CSC_DOMAINMANAGER]** Split logs when they contains several records
> [API_PARSER][CSC_DOMAINMANAGER] Split logs when they contains several records

- CHANGELOG
- vulture_os/toolkit/api_parser/harfanglab/harfanglab.py
- Add threshold check to avoid infinite loop when getting more than >=10k logs on single execution
> [API_PARSER][HARFANGLAB] Add threshold check to avoid infinite loop when getting more than >=10k logs on single execution

- CHANGELOG
- vulture_os/toolkit/api_parser/signalsciences_ngwaf/signalsciences_ngwaf.py
- Add site_name key in signalsciences_ngwaf logs
> [API_PARSER][SIGNALSCIENCES_NGWAF] Add site_name key in signalsciences_ngwaf logs

- CHANGELOG
- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/toolkit/api_parser/gatewatcher_alerts/gatewatcher_alerts.py
- vulture_os/toolkit/api_parser/utils.py
- [API_PARSER] [GATEWATCHER_ALERTS] New parser GATEWATCHER_ALERTS
>  [API_PARSER] [GATEWATCHER_ALERTS] New parser GATEWATCHER_ALERTS

- CHANGELOG
- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/toolkit/api_parser/cisco_umbrella/cisco_umbrella.py
- vulture_os/toolkit/api_parser/utils.py
- [API_PARSER] [CISCO_UMBRELLA] New parser CISCO-UMBRELLA
> [API_PARSER] [CISCO_UMBRELLA] New parser CISCO-UMBRELLA

- CHANGELOG
- vulture_os/toolkit/api_parser/proofpoint_trap/proofpoint_trap.py
- [**API_PARSER**][**PROOFPOINT_TRAP**] Fix missing key
> [API_PARSER][PROOFPOINT_TRAP] Fix missing key

- CHANGELOG
- vulture_os/services/config/pf.conf
- vulture_os/system/cluster/models.py
- vulture_os/toolkit/network/network.py
- vulture_os/toolkit/network/route.py
- [NETWORK] Automatically select the best interface for outgoing Backend/LogForwarders using system routes
> feat(network): automatically select the best NAT for outgoing flows

- CHANGELOG
- vulture_os/toolkit/api_parser/harfanglab/harfanglab.py
- [**HARFANGLAB**] Truncate `details_powershell.PowershellCommand` field & add is_truncated + add is_frombase64string fields
> [HARFANGLAB] Truncate details_powershell.PowershellCommand field & add is_truncated + add is_frombase64string fields

- CHANGELOG
- vulture_os/system/cluster/models.py
- [FRONTEND] [PF] Correctly add NAT rules for Forwarders on FILE/REDIS/KAFKA-type Frontends
> fix: Correctly add PF NAT rules for Forwarders on FILE/REDIS/KAFKA-type Frontends

- CHANGELOG
- vulture_os/services/frontend/form.py
- [GUI] [FRONTEND] Remove too strict validation for log_condition field
> [GUI] [FRONTEND] Remove too strict validation for log_condition field

- CHANGELOG
- vulture_os/services/frontend/models.py
- vulture_os/toolkit/api_parser/cybereason/cybereason.py
- [API_PARSER][CYBEREASON] Fix multiple points:
- Add a "to" argument to fetch malwares
- Add two distinct timestamps for malops & malwares
- Increment timestamp if no logs where retrieved during the last 24hours
> [API_PARSER][CYBEREASON] Fix multiple points

- CHANGELOG
- vulture_os/toolkit/api_parser/sentinel_one/sentinel_one.py
- [API_PARSER] [SENTINELONE] Properly get all techniques' names
> [SENTINEL_ONE] Fix to properly get all .indicators[].tactics[].techniques[].name

- CHANGELOG
- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/toolkit/api_parser/lockself/lockself.py
- vulture_os/toolkit/api_parser/utils.py
**Created**
- [API_PARSER][LOCKSELF] New API parser
> [API_PARSER][LOCKSELF] New API parser LOCKSELF

- CHANGELOG
- vulture_os/toolkit/api_parser/proofpoint_pod/proofpoint_pod.py
…lode ELK/OpenSearch limit number of fields
> [PROOFPOINT_POD] Remove metadata from additional.msgParts as they explode ELK/OpenSearch limit number of fields

- CHANGELOG
- vulture_os/toolkit/api_parser/cybereason/cybereason.py
- vulture_os/toolkit/api_parser/cybereason/malop.py
- vulture_os/toolkit/api_parser/cybereason/malware.py
- **[API_PARSER][CYBEREASON]** Refacto & split into smaller files + get bulk of max 1000 logs to avoid API error
> [API_PARSER][CYBEREASON] Refacto & split into smaller files + get bulk of max 1000 logs to avoid API error

- CHANGELOG
- vulture_os/toolkit/api_parser/cisco_umbrella/cisco_umbrella.py
- [**API_PARSER**][**CISCO_UMBRELLA**] - Add the list of users in cisco-umbrella logs
> [API_PARSER][CISCO_UMBRELLA] - Add the list of users in cisco-umbrella logs

- CHANGELOG
- vulture_os/authentication/user_portal/models.py
- [WORKFLOW] [MODELS] Revert deleted imports
> fix(workflow): Revert deleted imports

- CHANGELOG
- vulture_os/toolkit/api_parser/crowdstrike/crowdstrike.py
`AttributeError: 'NoneType' object has no attribute 'crowdstrike_request_incidents'`
> [API_PARSER][CROWDSTRIKE] Fix getAlerts on test

- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/toolkit/api_parser/cisco_umbrella_managed_org/cisco_umbrella_managed_org.py
- vulture_os/toolkit/api_parser/utils.py
**Created**
- [API_PARSER][API_CISCO_UMBRELLA_MANAGED_ORG] New API parser
> API_PARSER][API_CISCO_UMBRELLA_MANAGED_ORG] New API parser API_CISCO_UMBRELLA_MANAGED_ORG

- CHANGELOG
- vulture_os/system/cluster/api.py
- vulture_os/system/cluster/form.py
- vulture_os/system/templates/system/cluster_edit.html
- [SYSTEM] [NODE] Incompatible fields between api and form
> fix(system_node): broken api

- CHANGELOG
- vulture_os/system/cluster/models.py
- vulture_os/toolkit/network/network.py
- [NETWORK] Avoid defining NATing routes using loopback interfaces
> Fix loopback routing

- CHANGELOG
- vulture_os/system/pki/api.py
- vulture_os/system/pki/urls.py
- vulture_os/system/pki/views.py
- [SYSTEM] [PKI] Add post and delete requests
> add(system_pki): add post and delete requests

- CHANGELOG
- vulture_os/toolkit/api_parser/cortex_xdr/cortex_xdr.py
**Changed**
- [API_PARSER][CORTEX_XDR] Remove fields used for backward compatibility
> [API_PARSER][CORTEX_XDR] Remove fields used for backward compatibility

- CHANGELOG
- vulture_os/toolkit/api_parser/beyondtrust_pra/beyondtrust_pra.py
- [API_PARSER] [API_BEYONDTRUST_PRA] Add fields
> [API_PARSER] [API_BEYONDTRUST_PRA] Add fields

- CHANGELOG
- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/toolkit/api_parser/catonetworks/catonetworks.py
- vulture_os/toolkit/api_parser/utils.py
- [API_PARSER][CATONETWORKS] New parser
> [API_PARSER] New parser API_CATONETWORKS

- CHANGELOG
- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/toolkit/api_parser/infoblox_threat_defense/infoblox_threat_defense.py
- vulture_os/toolkit/api_parser/utils.py
- [**API_PARSER**] NEW parser **Infoblox_Threat_Defense**
> [API_PARSER] NEW parser Infoblox_Threat_Defense

- CHANGELOG
- vulture_os/services/templates/services/frontend_edit.html
[API_PARSER][CATONETWORKS] Fix template
> [API_PARSER][CATONETWORKS] Fix template

- CHANGELOG
- vulture_os/toolkit/api_parser/waf_cloudflare/waf_cloudflare.py
- [**API_PARSER**][**WAF_CLOUDFLARE**] Fix query '_fields_' field list to string
> [API_PARSER][WAF_CLOUDFLARE] Fix query 'fields' field list to string

- CHANGELOG
- vulture_os/toolkit/api_parser/cisco_duo/cisco_duo.py
- **[API_PARSER][CISCO_DUO]** Fix timestamp that was updated in any cases (even errors)
> [API_PARSER][CISCO_DUO] Fix timestamp updated in any cases (even errors)

- CHANGELOG
- vulture_os/daemons/monitor.py
- vulture_os/darwin/darwin.py
- vulture_os/services/filebeat/filebeat.py
- vulture_os/services/frontend/models.py
- vulture_os/services/frontend/views.py
- vulture_os/services/service.py
- [SERVICE] [FILEBEAT] Support new rc calls to check services separatly
> feat(filebeat): Support new rc calls to check services separatly

- CHANGELOG
- vulture_os/gui/static/js/listener.js
- vulture_os/services/templates/services/frontend_edit.html
- [SERVICES] [FRONTEND] Only show node field for specific modes
> fix(services_frontend): only show node field for specific modes

- CHANGELOG
- vulture_os/daemons/monitor.py
- vulture_os/services/frontend/models.py
- vulture_os/services/service.py
- [SERVICES] Improve how service statuses are reported
> [SERVICES] Improve how service statuses are reported

- CHANGELOG
- vulture_os/toolkit/api_parser/netskope/netskope.py
- **[NETSKOPE]** decrease in data recovery time range
> Apres tests sur l'api il semblerais que requeter plus de 10 minutes renvoi des doublons et ne renvoi pas toutes les donnees unique de la periode
> [API_PARSER][NETSKOPE] decrease in data recovery time range

- CHANGELOG
- vulture_os/toolkit/api_parser/cisco_meraki/cisco_meraki.py
- [API_PARSER][CISCO_MERAKI] Fix bug when 'get_security_logs' is False
- [API_PARSER][CISCO_MERAKI] Change common logger to warn instead of error
> [API_PARSER][CISCO_MERAKI] Fix and logger

- vulture_os/toolkit/api_parser/netskope/netskope.py
- [API_PARSER][NETSKOPE] Add logger for last_collected_timestamps update
> [API_PARSER][NETSKOPE] Add logger for last_collected_timestamps update

- CHANGELOG
- vulture_os/toolkit/api_parser/waf_cloud_protector/waf_cloud_protector.py
- [API_PARSER][WAF_CLOUD_PROTECTOR] Catch invalid lines + fix timestamp handling
> [API_PARSER][WAF_CLOUD_PROTECTOR] Catch invalid lines

- CHANGELOG
- vulture_os/toolkit/api_parser/cybereason/cybereason.py
- vulture_os/toolkit/api_parser/cybereason/malop.py
- [API_PARSER][CYBEREASON] Catch 204,500 HTTP codes + empty comments + empty machines + empty users
> [API_PARSER][CYBEREASON] Catch 204,500 HTTP codes

- CHANGELOG
- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/toolkit/api_parser/armis_centrix/armis_centrix.py
- vulture_os/toolkit/api_parser/utils.py
**[API_PARSER][ARMIS_CENTRIX]** Create new collector for Armis Centrix EDR (Alerts & Activity)
> [API_PARSER][ARMIS_CENTRIX] Create new collector for Armis Centrix EDR (Alerts & Activity)

- CHANGELOG
- requirements.in
- requirements.txt
- vulture_os/gui/crontab/generate_tzdbs.py
- vulture_os/gui/tests/test_generate_tzdbs.py
- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/frontend/views.py
- vulture_os/services/rsyslogd/config/timezone_offset.conf
- vulture_os/services/rsyslogd/rsyslog.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/toolkit/datetime/timezone.py
- vulture_os/toolkit/tests/test_timezone.py
- vulture_os/toolkit/updates/v2.23.0/0_generate_tzdbs.py
- vulture_os/vulture_os/settings.py
- [TIMEZONE] Allow to calculate current timezone offset for logs received on a Frontend
> feat(timezone): Allow to calculate current timezone offset for logs received on a Frontend

- vulture_os/toolkit/api_parser/armis_centrix/armis_centrix.py
[**ARMIS_CENTRIX**] Removes secret_key from collector's status logs
> [ARMIS_CENTRIX] Removes secret_key from collector's status logs

- CHANGELOG
- vulture_os/services/frontend/models.py
- vulture_os/services/frontend/views.py
- [SERVICES] [FRONTEND] Unable to delete config files due to wrong mode filtering
> fix(frontend): unable to delete config files due to wrong mode filtering

- CHANGELOG
- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/toolkit/api_parser/perception_point_x_ray/perception_point_x_ray.py
- vulture_os/toolkit/api_parser/utils.py
* [**API_PARSER**][**PERCEPTION_POINT_X_RAY**] New collector for Perception Point X Ray
> [API_PARSER][PERCEPTION POINT X RAY] New collector for Perception Point X Ray

- CHANGELOG
- vulture_os/services/frontend/form.py
- vulture_os/services/frontend/models.py
- vulture_os/services/templates/services/frontend_edit.html
- vulture_os/toolkit/api_parser/extrahop/extrahop.py
- vulture_os/toolkit/api_parser/utils.py
- [**API_PARSER**][**EXTRAHOP**] New collector
> [API_PARSER][EXTRAHOP] New collector

- CHANGELOG
- vulture_os/applications/logfwd/models.py
- vulture_os/daemons/monitor.py
- vulture_os/gui/crontab/api_clients_parser.py
- vulture_os/services/config/rsyslog_inputs.conf
- vulture_os/services/filebeat/filebeat.py
- vulture_os/services/frontend/models.py
- vulture_os/services/frontend/views.py
- vulture_os/services/haproxy/haproxy.py
- vulture_os/services/templates/services/frontends.html
- vulture_os/system/config/views.py
- vulture_os/toolkit/updates/v1.3.7/1_upgrade_filebeat_confs.py
- vulture_os/toolkit/updates/v1.3.9/1_upgrade_filebeat_confs.py
- vulture_os/toolkit/updates/v2.10.2/1_reload_log_filebeat_redis_frontends.py
- [FRONTEND] Allow to correctly play/pause manually any Frontend
> [FRONTEND] Correctly play/pause Frontends manually

- CHANGELOG
- vulture_os/services/frontend/config/haproxy_frontend.conf
- vulture_os/services/frontend/models.py
- [FRONTEND] [RSYSLOG] HAproxy config generation failure with new frontends
> fix(frontend): haproxy config generation failure with new frontends

- CHANGELOG
- vulture_os/toolkit/api_parser/cortex_xdr/cortex_xdr.py
[API_PARSER][CORTEX_XDR] Update timestamp of cortex_xdr API parser when there is no log during one day
> [API_PARSER][CORTEX_XDR] Update timestamp of cortex_xdr API parser when there is no log during one day

- CHANGELOG
- vulture_os/toolkit/api_parser/beyondtrust_pra/beyondtrust_pra.py
**[API_PARSER][BEYONDTRUST_PRA]** Catch invalid XML lines
> [API_PARSER][BEYONDTRUST_PRA] Catch invalid XML lines

- CHANGELOG
- vulture_os/portal/system/self_actions.py
- [PORTAL] [SELF_SERVICE] Disabled workflows listed
> [PORTAL] [SELF_SERVICE] Disabled workflows listed

- CHANGELOG
- vulture_os/toolkit/mongodb/mongo_base.py
- [MONGODB] Allow clusters with more than 7 nodes
> fix(mongodb): Allow clusters with more than 7 nodes

- CHANGELOG
- vulture_os/gui/static/js/darwin_policy_edit.js
- vulture_os/services/frontend/models.py
- vulture_os/services/rsyslogd/rsyslog.py
- [SERVICES] [FRONTEND] Weird bug in djongo
> fix(services): weird bug in djongo

- CHANGELOG
- vulture_os/services/config/rsyslog_inputs.conf
- vulture_os/services/filebeat/filebeat.py
- vulture_os/services/frontend/models.py
- vulture_os/services/frontend/views.py
- vulture_os/services/haproxy/haproxy.py
- vulture_os/services/rsyslogd/rsyslog.py
- [SERVICES] Prevent errors when deleted configuration files do not exist
---------
This PR also resolves some non-conformities introduced by #440
> Ensure Frontend configurations are deleted on disable

- vulture_os/toolkit/tests/test_api_parser.py
- [TESTING] [API_PARSER] New unit tests for ApiParser mother class
> Add unit testing for ApiParser main class

- CHANGELOG
- home/jails.apache/.zfs-source/home/vlt-os/scripts/add_to_hosts.py
- home/jails.apache/.zfs-source/home/vlt-os/scripts/wipe_node.sh
- vulture_os/gui/views/install.py
- vulture_os/system/cluster/api.py
- vulture_os/system/cluster/models.py
- vulture_os/system/generic_delete.py
- vulture_os/system/pki/models.py
- vulture_os/system/templates/system/cluster.html
- vulture_os/templates/generic_delete.html
- vulture_os/toolkit/mongodb/mongo_base.py
- vulture_os/toolkit/network/network.py
- vulture_os/toolkit/redis/redis_base.py
- [SCRIPT] [WIPE] New script to reset a bootstrapped node
- [CLUSTER] Improve node import routine
- [CLUSTER] Improve node deletion from the gui
> feat(cluster): improve cluster management

- CHANGELOG
- vulture_os/toolkit/api_parser/gatewatcher_alerts/gatewatcher_alerts.py
- [**API_PARSER**][**GATEWATCHER_ALERTS**] Merge `raw_alert` into `alert` dict
> [API_PARSER][GATEWATCHER_ALERTS] Merge `raw_alert` into `alert` dict

- CHANGELOG
- vulture_os/toolkit/api_parser/armis_centrix/armis_centrix.py
**[API_PARSER][ARMIS_CENTRIX]** Collect at max 1h of range to avoid API taking too long to answer
> [API_PARSER][ARMIS_CENTRIX] Collect at max 1h of range to avoid API taking too long to answer

- CHANGELOG
- vulture_os/toolkit/api_parser/nozomi_probe/nozomi_probe.py
[API_PARSER][NOZOMI_PROBE] Fix type error when the field total contains null value
> [API_PARSER][NOZOMI_PROBE] Fix type error when the field total contains null value

- CHANGELOG
- vulture_os/toolkit/api_parser/armis_centrix/armis_centrix.py
**[API_PARSER][ARMIS_CENTRIX]** Fix condition to ask for a new token
> [API_PARSER][ARMIS_CENTRIX] Fix condition to ask for a new token

- vulture_os/toolkit/api_parser/hornetsecurity/hornetsecurity.py
[HORNETSECURITY] Add missing proxies/verify parameters to get_hierarchy_id()
> [HORNETSECURITY] Add missing proxies/verify parameters to get_hierarchy_id()

- CHANGELOG
- vulture_os/toolkit/api_parser/trendmicro_visionone/trendmicro_visionone.py
- [API_PARSER][TRENDMICRO_VISIONONE] Last api call was not updated
> [API_PARSER] [TRENDMICRO_VISIONONE] HOTFIX :: Update last_api_call

- CHANGELOG
- vulture_os/toolkit/api_parser/cortex_xdr/cortex_xdr.py
- [API_PARSER] [CORTEX_XDR] Last api call was not updated
> fix(collector_cortex_xdr): Correctly update timestamps

- CHANGELOG
- vulture_os/toolkit/api_parser/beyondtrust_reportings/beyondtrust_reportings.py
**[API_PARSER] [BEYONDTRUST_REPORTINGS]** Fix parsing of support session logs
> [API_PARSER] [BEYONDTRUST_REPORTINGS] Fix parsing of support session logs

- CHANGELOG
- vulture_os/toolkit/api_parser/proofpoint_pod/proofpoint_pod.py
[API_PARSER] [PROOFPOINT_POD] Add one second to the last_api_call to avoid duplication
> [API_PARSER] [PROOFPOINT_POD] Add one second to the last_api_call to avoid duplication

- CHANGELOG
- vulture_os/toolkit/api_parser/perception_point_x_ray/perception_point_x_ray.py
- **[API_PARSER][PERCEPTION_POINT_X_RAY]** Improve error message
> [API_PARSER][PERCEPTION_POINT_X_RAY] Improve error message

- CHANGELOG
- vulture_os/toolkit/api_parser/gatewatcher_alerts/gatewatcher_alerts.py
**[API_PARSER][GATEWATCHER_ALERTS]** Update endpoints of the API
> [API_PARSER][GATEWATCHER_ALERTS] Update endpoints of the API

- CHANGELOG
- vulture_os/toolkit/api_parser/sentinel_one_graph/sentinel_one_graph.py
Change's preview :
- adds alert filtering by `detectionSource.product` value,
- `format_log() `enhancement (`comments` fetching, `mitre_tactic/techniques` rename, `needs_attention` bool crafting, `createdAt` date parsing)
- `get_itdr_alert_details()` more fields gathered,
> [SENTINEL_ONE_IDENTITY_GRAPH] Improve collector based on new EdB

- vulture_os/services/config/rsyslog_inputs.conf
- [RSYSLOG] Load new module 'mmutf8fix' in initial configuration
> [RSYSLOG] Load new module 'mmutf8fix'
