vulture_os/gui/static/js/listener.js
vulture_os/services/frontend/form.py
vulture_os/services/frontend/models.py
vulture_os/services/rsyslogd/config/rsyslog_darwin/ruleset.conf
vulture_os/services/templates/services/frontend_edit.html

- add a 'darwin_mode' parameter when a darwin policy is added to a Listener
- 'darwin_mode' has 2 options:
- 'generate alerts' (mmdarwin 'darwin'), sends data to the filter and doesn't wait for an answer (data is propagated to potential chained filters)
- 'enrich logs and generate alerts' (mmdarwin 'both'), waits for the filter to reply with the certitude(s) (data is propagated to chained filters)
- fix 'input_log_type' parameter to only show for the right mode

FRONTEND:: add the 'darwin_mode' parameter, and fix to JS

---

vulture_os/services/frontend/config/haproxy_frontend.conf
vulture_os/system/pki/models.py

- ACL: allow Host header with a  custom explicit port (example: allow both 'vulture.local' and 'vulture.local:1234')
- Listener with TLS profile: fix bug when using certificate with spaces in name

WORFLOW:: FIXES TO ACLS AND CERTIFICATE LOAD

---

vulture_os/daemons/monitor.py
vulture_os/services/strongswan/api.py
vulture_os/services/strongswan/models.py
vulture_os/services/strongswan/urls.py
vulture_os/services/strongswan/views.py

- [IPSEC] [GUI] default name "Ipsec configuration" for ipsec objects
- [IPSEC] [API] 'enabled' field is returned in object's data
- [IPSEC] [API] can get an Ipsec configuration with its related node id
- [IPSEC] [GUI + API] Could not create a new configuration
- [IPSEC] [SERVICE] no old tunnel statuses remain after a refresh

IPSEC:: various fixes and improvements

---

vulture_os/darwin/policy/models.py
vulture_os/darwin/templates/policy_edit_v2.html
vulture_os/gui/static/js/darwin_policy_edit.js

- [GUI] [Darwin] enrichment tags are always available and can always be set
- [GUI] [Darwin] if enrichment tags are set on a filter, those tags will always be in the generated alerts

GUI_DARWIN::MODIFIED:: Can always set enrichment tags to a filter, those tags will always be in the alert

---

vulture_os/authentication/generic_delete.py
vulture_os/authentication/ldap/tools.py
vulture_os/authentication/openid/form.py
vulture_os/authentication/openid/models.py
vulture_os/authentication/openid/views.py
vulture_os/authentication/user_portal/views.py

- [IDP] [PROVISIONING] return 404 if user does not exist during deletion
- [USER PORTAL] [GUI] preserve scopes during portal copies
- [OPENID] [API] allow giving scopes as json array
- [IDP PORTAL] Don't overwrite Connector name when modifying linked IDP Portal
- [PORTAL] reload Frontend configuration when removing a related IDP portal to avoid future errors on Haproxy configuration tests
- [LDAP] [GUI] Don't allow repository removals if still referenced by a Portal
- [Portal] [GUI] Don't allow removals if still referenced by a workflow or another portal
- [OpenID [GUI] Don't allow removals if still referenced by a portal

Version 1.2.9

---

vulture_os/darwin/policy/api.py
vulture_os/gui/static/js/darwin_policy_edit.js
vulture_os/services/config/darwin.conf
vulture_os/services/rsyslogd/config/rsyslog_darwin/ruleset.conf

- [RSYSLOG] [DARWIN] [CONF] buffer inputs could contain too much entries
- [DARWIN] [CONF] general Darwin configuration was incorrect when no filters were configured
- [DARWIN] avoid recreating filters when editing policies in GUI or on APIs
- [DARWIN] [GUI] Properly copy filters when copying a policy (don't reuse filters from copied one)

Darwin : avoid recreating filters when editing policies

---

vulture_os/darwin/policy/api.py
vulture_os/gui/static/js/darwin_policy_edit.js
vulture_os/services/config/darwin.conf
vulture_os/services/rsyslogd/config/rsyslog_darwin/ruleset.conf

- [RSYSLOG] [DARWIN] [CONF] buffer inputs could contain too much entries
- [DARWIN] [CONF] general Darwin configuration was incorrect when no filters were configured
- [DARWIN] avoid recreating filters when editing policies in GUI or on APIs
- [DARWIN] [GUI] Properly copy filters when copying a policy (don't reuse filters from copied one)

Version 1.2.10

---

vulture_os/gui/static/js/listener.js
vulture_os/services/frontend/views.py
vulture_os/toolkit/api_parser/cortex_xdr/cortex_xdr.py
vulture_os/toolkit/api_parser/reachfive/reachfive.py

- [LOGAPI] [CORTEX XDR] Prevent getting last log line repeatedly
- [LOGAPI] [REACHFIVE] Properly get most recent date from all logs received
- [FRONTEND] [RSYSLOG CONF] Remove old ruleset file when ruleset is changed in 'filebeat' mode
- [FRONTEND] [GUI] Allow selecting a ruleset when in mode 'filebeat' and type 'Vendor Specific API'

Beta 1.3.6

---

vulture_os/toolkit/api_parser/harfanglab/harfanglab.py

- [API_PARSER][HARFANGLAB] Isoformat already setting timezone - prevent invalid timestamp format

Release 1.5.1

---

vulture_os/services/frontend/config/haproxy_frontend.conf
vulture_os/services/frontend/models.py
vulture_os/services/frontend/views.py
vulture_os/services/haproxy/haproxy.py
vulture_os/system/cluster/api.py
vulture_os/system/cluster/models.py
vulture_os/system/cluster/urls.py

- [FRONTEND]
-  Add 'validate' boolean parameter to disable config testing
- Improve performances by reloading frontend config asynchronously
- Refactor jinja template haproxy_frontend for better performances
- [API][CLUSTER] Add supervision api endpoint to get tasks
- [API][CLUSTER] Add supervision api endpoint to get cluster/node status (pending tasks, frontend statuses)
- [VULTURED] Update status of task if an error occured (status was let 'running' forever)

Frontend reload asynchronously + new supervision endpoints 

---

home/jails.apache/.zfs-source/usr/local/etc/gunicorn.d/portal.conf.py
home/jails.apache/.zfs-source/usr/local/etc/rc.d/gunicorn
vulture_os/services/frontend/config/haproxy_frontend.conf
vulture_os/toolkit/updates/v1.7.0/0_migrate_portal_gunicorn.sh
vulture_os/toolkit/updates/v1.7.0/1_reload_frontends_conf.py

- [HAProxy][Frontend] Fix acl syntax according to last haproxy version
- [PORTAL] Use **[gunicorn](https://docs.gunicorn.org/en/stable/)** instead of **[apache wsgi](https://pypi.org/project/mod-wsgi/)** to host portal engine

Release 1.7.0

---

home/jails.apache/.zfs-source/usr/local/etc/gunicorn.d/portal.conf.py

- [PORTAL] [GUNICORN CONF] service didn't listen on jail's IPv6 address (no connection from IPv6 networks)

GUNICORN::FIXED:: gunicorn did not listen on IPv6 jail address

---

vulture_os/authentication/idp/api.py
vulture_os/portal/system/authentications.py
vulture_os/portal/system/redis_sessions.py
vulture_os/portal/system/self_actions.py
vulture_os/portal/views/logon.py
vulture_os/toolkit/auth/ldap_client.py

- [PORTAL] ensure the session stays valid for at least 5 minutes when requesting double-authentication on a portal
- [IDP] set reset password URL validity to 72 hours
- [PORTAL] correctly set 'iat' field in token
- [SELF_SERVICE] avoid errors during password change when user does not exist

Portal fixes

---

vulture_os/toolkit/api_parser/reachfive/reachfive.py

- [REACHFIVE] Fix last_api_called not updated after 10K events

FIX : last_api_called not updated after 10K events

---

vulture_os/portal/views/logon.py
vulture_os/toolkit/system/hashes.py

- [PORTAL] Create a new portal session value from safe generator if value taken from client cookies is not formatted correctly or is not present in current cache
- [UTILS] [ HASHES] validation function for hash digest's format (length and characters used)

Hotfix:: Validate portal session's format and presence in cache, or create a new value

---

vulture_os/toolkit/api_parser/akamai/akamai.py

### Fixed
- [API_PARSER][AKAMAI] Properly acquire data_lock during internal last_log_time updates

FIX: properly acquire data lock during date updates in multi-threaded api akamai log parser

---

vulture_os/authentication/openid/form.py
vulture_os/authentication/openid/models.py
vulture_os/authentication/openid/views.py

- Fixed testing already configured OpenID
- Reason: test_provider function uses a ModelForm from the Model OpenIDRepository that had Unique constraint on the fields: provider, client_id and client_secret.
- Prevented suggestion of previous OpenID client secrets

FIX::Retesting already configured OpenID

---

vulture_os/authentication/idp/api.py
vulture_os/authentication/idp/authentication.py
vulture_os/authentication/idp/urls.py
vulture_os/authentication/ldap/tools.py
vulture_os/authentication/user_portal/models.py
vulture_os/portal/system/authentications.py
vulture_os/portal/system/redis_sessions.py
vulture_os/portal/views/logon.py
vulture_os/toolkit/auth/ldap_client.py
vulture_os/vulture_os/settings.py

- [LDAP_CLIENT] Use escape_dn_chars() instead of escape_filter_chars() in search_user() for sanitation
- [OAUTH] Ensure 'sub' is present in oauth2 tokens
- [IDP_API] Improved logging to include systematic portal, repo, user (when available) and action
- [IDP] [API] New APIs to manage oauth2 tokens creation
- Create a new token for a specific user, on a specific portal and repository
- User must authenticate themselves with a valid oauth token
- Claims will be created using internal repository data and IDP scope filtering
- Expiration time can be overridden during POST/PATCH
- Tokens can be deleted by user, they will be removed if user is removed
- [LDAP] [TOOLS] Utility function to get a user by its full DN
- [REDIS] [TOKENS] Utility function to check if a key exists in Redis
- …

Api oauth tokens

---

CHANGELOG
home/jails.apache/.zfs-source/home/vlt-os/scripts/pkg_upgrade.sh
home/jails.apache/.zfs-source/usr/local/etc/apache24/gui-httpd.conf
home/jails.apache/.zfs-source/usr/local/etc/apache24/portal-httpd.conf
home/jails.apache/.zfs-source/usr/local/etc/secadm.rules
home/jails.portal/.zfs-source/usr/local/etc/rc.d/gunicorn
home/jails.portal/.zfs-source/usr/local/etc/secadm.rules
vulture_os/authentication/idp/api.py
vulture_os/authentication/idp/urls.py
vulture_os/authentication/user_portal/api.py
vulture_os/portal/system/authentications.py
vulture_os/portal/system/redis_sessions.py
vulture_os/portal/views/logon.py
vulture_os/services/config/spoe_session.txt
vulture_os/toolkit/api_parser/crowdstrike/crowdstrike.py
vulture_os/toolkit/api_parser/gsuite_alertcenter/gsuite_alertcenter.py
vulture_os/toolkit/api_parser/sentinel_one/sentinel_one.py
vulture_os/toolkit/updates/v2.1.0/0_upgrade_python.sh
vulture_os/toolkit/updates/v2.1.1/0_update_apache_config.sh

- [PORTAL] [SSO] SSO could fail when portal have no oauth2 activated
- [PORTAL] Correctly refresh session timeout only when necessary
- [APACHE] [CONFIGURATION] Update Apache WSGI's configuration to allow code to read 'Authorization' header
- [API_PARSER] [SENTINEL_ONE] Avoid parser getting stuck after not having received any logs for more than 24h
- [API_PARSER] [GSUITE] Parser failure caused by wrong 'since' variable type
- [API_PARSER] [CROWDSTRIKE] Parser failure caused by wrong 'since' variable type
- [USER_PORTAL] [API] Could not get all portals through API when no ID/name was specified
- [PORTAL] Validate session Cookies, then Vulture Headers, then 'Authorization' Header during session validation
- Allows protected applications to use 'Authorization' Headers when a user browses it …

Version 2.1.1

---

vulture_os/toolkit/api_parser/symantec/symantec.py

- [API_PARSER][Symantec]  Don't use token if it's older than 24h, seems to be expired

API_PARSER :: Symantec : Fix token expiration 

---

vulture_os/toolkit/api_parser/crowdstrike/crowdstrike.py

- [API_PARSER][Crowdstrike] Prevent last_api_call stagnation if no events where retrieved during the last 24h

API_PARSER :: Crowdstrike : Fix last_api_call stagnation

---

vulture_os/toolkit/api_parser/imperva/imperva.py

- [**API_PARSER**][**Imperva**] Prevent infinite download loop when a file cannot be decoded - last_log_file where never set due to missing try/except

API_PARSER :: Imperva : Add missing try/except

---

vulture_os/toolkit/api_parser/crowdstrike/crowdstrike.py

Fix: Add api_host to 'url' event log field

Fix crowdstrike api

---

vulture_os/toolkit/api_parser/crowdstrike/crowdstrike.py

- [PAR_PARSER][Crowdstrike] Typo error - last_api_call were not properly updated

[API_PARSER][Crowdstrike] Fix typo

---

CHANGELOG
vulture_os/applications/backend/models.py
vulture_os/services/frontend/models.py
vulture_os/services/frontend/views.py
vulture_os/system/generic_delete.py
vulture_os/system/pki/views.py

- Once the TLS profile form is received, all Listners and Applications are scanned to verify if the profile is related to them and reload the config files when needed to match the update.
- It is now impossible to delete a TLS profile used in a frontend or a backend
- The delete template will list all the listeners who use the TLS profile
- When selecting plain text for a frontend, it is handled as http

FIX::TLS:Modifying a profile update frontend and backend config

---

vulture_os/toolkit/api_parser/imperva/imperva.py

- [API_PARSER][IMPERVA] Prevent infinite download loop when logs index cannot be downloaded - last_log_file where never set due to missing try/except

[API_PARSER][Imperva] Prevent downloading same files

---

vulture_os/toolkit/api_parser/netskope/netskope.py

[API_NETSKOPE] Break the loop of the logs request when there is no logs

API_NETSKOPE::fix infinite loop when there is no log

---

vulture_os/toolkit/api_parser/cybereason/cybereason.py

Add a delay before request API cybereason, to let enough time at cybereason to put all logs available

[API_PARSER] CYBEREASON Delay request at the API

---

vulture_os/toolkit/api_parser/gsuite_alertcenter/gsuite_alertcenter.py

- [API_PARSER][GSuite_AlertCenter] Prevent last_api_call stagnation if no events where retrieved during the last 24h

[API_PARSER][GSuite_AlertCenter] Fix last_api_call stagnation

---

vulture_os/toolkit/api_parser/imperva/imperva.py

Don't logs error when the file to retrieve doesn't exist to avoid false alert

[API_PARSER] IMPERVA Fix logger error

---

CHANGELOG
vulture_os/system/pki/views.py

- [SYSTEM] [CERTIFICATES] Protect used certificates when attempted to be deleted

CERTS::FIXED: protect used certificates on delete request

---

CHANGELOG
vulture_os/toolkit/api_parser/crowdstrike/crowdstrike.py

- [API_COLLECTOR][Crowdstrike] Delay query time of 2 minutes - to avoir missing events

[API_COLLECTOR][Crowdstrike] :: Fix : Delay query time

---

CHANGELOG
vulture_os/portal/system/sso_clients.py
vulture_os/portal/views/logon.py

- [SSO_CLIENT] [COOKIES] Fix cookies' banning when receiving application's response
- [SSO_CLIENT] [COOKIES] Correctly check the 'HttpOnly' attribute set from application's response
- [IDP] [COOKIES] Ensure 'HttpOnly' attribute is always set on IDP session cookies

COOKIES: ensure cookies' security is preserved

---

CHANGELOG
vulture_os/toolkit/api_parser/ms_sentinel/ms_sentinel.py

- [**MS_SENTINEL**]
+ **Not intended changes** Fix **entities** gathering using `incident.entities` rather than `incident.value` as source dictionary field and use `incident.name` instead of incident.id to fetch content from API
+ Evol to use `properties.processingEndTime` instead of `properties.timeGenerated` to determine if alert is an outdated one

[MS_SENTINEL] Evol to use new alert_time as outdated alert check & fix entities gathering

---

CHANGELOG
vulture_os/applications/logfwd/views.py
vulture_os/services/frontend/models.py

- [LOG_FORWARDER] Rsyslog config generation error when '-' found in LOGOM name
- [LOG_FORWARDER] Frontends configs aren't refreshed when LOGOM used as parse failure

[LOGOM] Fix bugs related to names and dependencies

---

vulture_os/toolkit/api_parser/nozomi_probe/nozomi_probe.py

- [COLLECTOR][NOZOMI_PROBE] API requires timestamp as integer, not as float.

[NOZOMI_PROBE]: Fix invalid timestamp in query

---

CHANGELOG
vulture_os/services/frontend/models.py
vulture_os/services/frontend/views.py

- [FRONTEND] Allow skipping unresponsive nodes during HAProxy test_conf

[FRONTEND] Allow skipping unresponsive nodes during HAProxy test_conf

---

CHANGELOG
vulture_os/toolkit/api_parser/trendmicro_visionone/trendmicro_visionone.py

- Add `status` in execute_query() to not insert in rsyslog/update timestamp if we've encountered an error while gathering logs
- Raise pagination limit on alerts and audits logs from `50` to `200` and `5000` to oat logs to reduce requests count
- Update gathering range from `1 day` to `1 minute`, causing extremely long querying in `while true` to browse all pages - triggering `429 Too Many Requests` (rate-limit) while restarting from a long time
- Delay gathering using `while to <= timezone.now() - timedelta(minutes=5): do get_logs()` because API doesn't serve all logs at real-time (another solution would be to use parameter ingestedStartDateTime & ingestedEndDateTime for querying log in the last hour range only, and detectedStartDateTime & detectedEndDateTime for more olders)

[API_TRENDMICRO_VISIONONE] Various fixes

---

CHANGELOG
vulture_os/toolkit/api_parser/nozomi_probe/nozomi_probe.py

[**NOZOMI_PROBE**] 
- Add `Content-Type` and `Accept` headers 
- Override `User-Agent` one, because when it contains the exact following string `(python-requests/2.31.0)` Nozomi weirdly seems to block the request using a rule based on this pattern, thus total field is equal to null causing collection crash because we've tried to compare int with NoneType at next execution

[NOZOMI_PROBE] Add custom headers and override User-Agent to avoid Nozomi ban

---

CHANGELOG
vulture_os/toolkit/api_parser/retarus/retarus.py

- [**RETARUS**] Fix bad json formatting leading to escaped string sended over rsyslog

[API_PARSER][RETARUS] Fix bad json formatting leading to escaped string sended over rsyslog

---

CHANGELOG
vulture_os/services/frontend/views.py
vulture_os/toolkit/api_parser/api_parser.py

- [API_PARSER] Wrongly select custom parser certificate when verification is disabled

API_PARSER::FIXED: custom parser certificate deselection

---

CHANGELOG
vulture_os/toolkit/api_parser/gatewatcher_alerts/gatewatcher_alerts.py

- [API_PARSER][GATEWATCHER_ALERTS] Avoid missing logs by setting the last_api_call the timestamp of the last retrieved log

[API_PARSER][GATEWATCHER_ALERTS] Avoid missing logs by setting the last_api_call the timestamp of the last retrieved log

---

CHANGELOG
vulture_os/toolkit/api_parser/harfanglab/harfanglab.py

- [API_PARSER] [HARFANGLAB] Hotfix to add a check when powershell_command object is None

[API_HARFANGLAB] Hotfix to add a check when powershell_command is None

---

CHANGELOG
vulture_os/toolkit/api_parser/nozomi_probe/nozomi_probe.py

- [API_PARSER] [NOZOMI_PROBE] Update timestamp when no logs received during last 24h

[API_PARSER] [NOZOMI_PROBE] Update timestamp when no logs received during last 24h

---

CHANGELOG
vulture_os/toolkit/api_parser/harfanglab/harfanglab.py

- **[API_PARSER][HARFANGLAB]** Truncate fields with more of 16384 chars

[API_PARSER][HARFANGLAB] Truncate fields with more of 16384 chars

---

CHANGELOG
vulture_os/toolkit/api_parser/cybereason/malop.py

**[API_PARSER][CYBEREASON]** Avoid None evaluation of log objects (users and devices) in format_log for malops

[API_PARSER][CYBEREASON] Avoid None evaluation of log objects in format_log for malops

---

CHANGELOG
vulture_os/toolkit/api_parser/crowdstrike/crowdstrike.py

**[API_PARSER][CROWDSTRIKE]** Fix infinite loop when we encounters more than 100 logs (default limit) in one request.
- Use the size of already received logs as `offset` parameter to paginate instead of trusting the API return (that is always 0) & add `update_lock()` in case long pagination looping
- Raise an exception if status_code not in [200, 201] instead of shadow error that don't stop collector execution

[API_PARSER][CROWDSTRIKE] Fix offset in case of >=100 logs gathering

---

CHANGELOG
vulture_os/toolkit/api_parser/cortex_xdr/cortex_xdr.py

- [API_PARSER] [CORTEX_XDR] Use the 'local_insert_ts' field as time field for alerts
- [API_PARSER] [CORTEX_XDR] Bound requests with a 'to' parameter
- [API_PARSER] [CORTEX_XDR] Avoid missing logs when fetching pages by changing the 'since' filter
- [API_PARSER] [CORTEX_XDR] Avoid missing first log of each next page in queries
- [API_PARSER] [CORTEX_XDR] Avoid getting multiple times the same event during consecutive runs

[API_PARSER][CORTEX_XDR] Fix several issues

---

CHANGELOG
vulture_os/toolkit/api_parser/gatewatcher_alerts/gatewatcher_alerts.py

- [API_PARSER][GATEWATCHER_ALERTS] Add 'host' field in json logs (requested url's domain)

[API_PARSER][GATEWATCHER_ALERTS] Add 'host' field in json logs

---

CHANGELOG
vulture_os/toolkit/api_parser/waf_cloudflare/waf_cloudflare.py

- [API_PARSER][WAF_CLOUDFLARE] Fix invalid time range requested for UTC-* consoles

[API_PARSER][WAF_CLOUDFLARE] Fix invalid 'test' time range

---

CHANGELOG
vulture_os/toolkit/api_parser/cisco_duo/cisco_duo.py

[CISCO_DUO] Fix doublon logs generated by non-incrementation of last_api_call by one second & prevent non-declaration of since

[CISCO_DUO] Fix doublon logs generated by non-incrementation of last_api_call by one second & prevent non-declaration of since

---

CHANGELOG
vulture_os/toolkit/api_parser/crowdstrike/crowdstrike.py

[**CROWDSTRIKE**] Migrate v1->v2 endpoints
- Clean old code
+ Remove `get*()` methods as fields issued from are not captured in logs,
+ Split `getAlerts()` to `get_detections()` and `get_incidents()` methods,
+ Remove the `customLimit` return limit (defaulted to -1 to not paginate on the first request) - and set it to 1000,
- Migrate v1 (as they are now deprecateds) endpoints to v2
+ The 'filter' and `sort` parameters are now based on `updated_timestamp`, `data_domains` and `product`,
+ `composite_ids` replace `ids` parameters to get logs (the second in `get_*` methods),
+ Enrich `get_incidents` method by conditionally getting `hosts` field from `entities.agent_ids` field and "devices/entities/devices/v2" endpoint,
+ Split logs by bulk of 1000 to avoid error if we try to request more,
+ …

[CROWDSTRIKE] Migrate v1->v2 endpoints

---

CHANGELOG
vulture_os/services/frontend/form.py
vulture_os/services/frontend/models.py
vulture_os/services/templates/services/frontend_edit.html
vulture_os/toolkit/api_parser/hornetsecurity/hornetsecurity.py
vulture_os/toolkit/api_parser/utils.py

[HORNETSECURITY] New collector
- Gets emails ("https://cp.hornetsecurity.com/api/v0/emails/_search/") and auditings logs ("https://cp.hornetsecurity.com/api/v0/auditing/_search/") unconditionnaly using `object_id` previously fetched by a call to ("https://cp.hornetsecurity.com/api/v0/hierarchy/"),
- Get rid of 10k log limit by diving time-range by two, if there is more than 10k log to fetch, thus catching the case before the error is sended by the API to the client,

[HORNETSECURITY] New collector

---

CHANGELOG
vulture_os/gui/crontab/api_clients_parser.py
vulture_os/toolkit/api_parser/api_parser.py
vulture_os/toolkit/api_parser/blackberry_cylance/blackberry_cylance.py

**[API_PARSER] [BLACKBERRY_CYLANCE]** Wait 60s when we encounter a 429 error

[API_PARSER] [BLACKBERRY_CYLANCE] Wait 60s when we encounter a 429 error

---

CHANGELOG
vulture_os/services/config/pf.conf
vulture_os/services/pf/models.py
vulture_os/system/netif/views.py

- [PF] [CONF] Add missing CARP rule to allow inter-cluster broadcasting and enable correct MASTER/BACKUP switch
- [NET] [CARP] Correctly clean system configurations when removing some interface(s) from an existing CARP conf
- [NET] [CARP] Correctly use existing carp password and priorities for added interface(s) on an existing CARP conf

fix(carp): Add missing PF rule for inter-cluster CARP synchronization

---

CHANGELOG
vulture_os/services/frontend/models.py

- [**FRONTEND**] Adjust "http_path" of log-format directive, %HP has changed since HAProxy v2.4

[FRONTEND][LOG-FORMAT] Adjust http_path of log-format
